{% set name = "sas7bdat-converter" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sas7bdat_converter-{{ version }}.tar.gz
  sha256: 11227c2707b6c423427cf00c151c7eb8c0af01e3c87b0790b3e5c656f489e32c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core >=1.0
  run:
    - python >=3.7,<4.0
    - pandas >=1.2.0
    - openpyxl >=3.0.5
    - pyarrow >=8.0.0

test:
  imports:
    - sas7bdat_converter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sanders41/sas7bdat-converter
  summary: Convert sas7bdat and xport files into other formats such as parquet, csv, json, and Excel
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
